### ISSUE TITLE
NoSuchFieldException "elementData" on JavaFXPorts in release 1.4.3 / 1.5

### ISSUE THREAD

**Issue by m3n4c3** [streamsupport/streamsupport#4]
When I call StreamSupport.stream(someArrayList).forEach(someLamda) this Exception gets thrown.

I'm using Android 5.0 on a Samsung Galaxy S5.

Can you please explain this Error and/or how to fix it?

Thank you!

Stacktrace:

    07-01 16:29:18.736: E/AndroidRuntime(27444): java.lang.Error: java.lang.NoSuchFieldException: elementData
    07-01 16:29:18.736: E/AndroidRuntime(27444): 	at java8.util.ArrayListSpliterator.<clinit>(ArrayListSpliterator.java:211)
    07-01 16:29:18.736: E/AndroidRuntime(27444): 	at java8.util.Spliterators.listSpliterator(Spliterators.java:918)
    07-01 16:29:18.736: E/AndroidRuntime(27444): 	at java8.util.Spliterators.spliterator(Spliterators.java:898)
    07-01 16:29:18.736: E/AndroidRuntime(27444): 	at java8.util.stream.StreamSupport.stream(StreamSupport.java:99)

**Comment by stefan-zobel** [comment]
Which streamsupport release / version do you use?

**Comment by stefan-zobel** [comment]
```
    /**
     * Used to detect the presence or absence of android.util.DisplayMetrics
     * and other classes. Gets employed when we need to establish whether we
     * are running on Android and, if yes, whether the version of Android is
     * based on Apache Harmony or on OpenJDK.
     * 
     * @param name
     *            fully qualified class name
     * @return {@code true} if class is present, otherwise {@code false}.
     */
    private static boolean isClassPresent(String name) {
        Class<?> clazz = null;
        try {
            // avoid <clinit> which triggers a lot of JNI code in the case
            // of android.util.DisplayMetrics
            clazz = Class.forName(name, false, Spliterators.class.getClassLoader());
        } catch (Throwable notPresent) {
            // ignore
        }
        return clazz != null;
    }

```

Please run this method with the arguments

a) `"android.util.DisplayMetrics"`
b) `"java.util.function.Function"`

and tell me the output (true/false) for a) and b)


Thanks,
Stefan

**Comment by stefan-zobel** [comment]
You also wanted an explanation of this error.

There are 3 possible cases with respect to the detection whether streamsupport is executed on Android or not


```
1:   a) true,  b) false       ==> running on Android, API level 22 or lower

2:   a) true,  b) true        ==> running on Android, API level 23 or higher

3:   a) false, b) true/false  ==> NOT running on Android
```


Your result seems to be either 2 or 3. That is, streamsupport assumes it gets executed on an OpenJDK-compatible Java VM (case 3) or on Android N (case 2) where the private Object[] member in j.u.ArrayList is named "elementData".

But on Android 5 (case 1) the Object[] member is named "array", hence the NoSuchFieldException.

**Comment by stefan-zobel** [comment]
Another possibility: perhaps too aggressive proguard shrinking options? Try without!

And where did you get the streamsupport jar from? Maven Central / official sourceforge site?

Please don't forget to tell me which streamsupport version you are using.

**Comment by m3n4c3** [comment]
Thanks for the fast and extensive reply :+1: 
I'm using version 1.4.3

the result is a) true b) true

And I think I also know the Reson:  
I'm using JavaFXPorts - a framework that makes javafx applications runnable on android.  
This framework **DOES NOT** implement Streams (that's why I use this lib) **BUT** it **DOES** implement some functional stuff like _Consumer_, _Optional_, etc.

My guess is that it has the function class and so your library detects it as the wrong android version.

Which leaves me with my question:  
With what we know now, how _can_ we/I fix it?

**Comment by stefan-zobel** [comment]
Yes. a) true b) true infers Android Nougat which means "elementData".

There's nothing I can do at the moment to change this situation on 1.4.3 or 1.5

Nevertheless, you might be lucky: please try with release **1.4.2** instead.

The `"java.util.function.Function"` check was introduced in 1.4.3 whereas 1.4.2 used another technique: It checks for the presence of `"org.apache.harmony.security.PublicKeyImpl"` to conclude that it must be an Apache Harmony based Android. That used to work on early Android N developer previews but doesn't anymore. That's the reason why I changed it to "java.util.function.Function".

1.4.2 should work in your case - but only as long as you _don't_ try to run on Android Nougat!

I didn't know that JavaFxPorts has a "java." API (and I doubt that it is a good idea).

Please let me know whether 1.4.2 works for you.

I might be able to change the situation in the next release (1.5.1) but don't have an approach right now.

If you have follow-up questions or issues please use the official sourceforge site: https://sourceforge.net/projects/streamsupport/ There is a discussion forum and the possibility to create tickets.

Thanks,
Stefan

**Comment by stefan-zobel** [comment]
I've logged an issue: `"Android Harmony detection fails when JavaFXPorts is present"
`

See https://sourceforge.net/p/streamsupport/tickets/210/

Maybe you could do a test for me by the time I have an interim version that should fix this issue?

**Comment by stefan-zobel** [comment]
Please find attached an _interim_ version of **1.5.1** that should fix your problem (it now tests for the presence of `"java.util.stream.BaseStream"` instead of `"java.util.function.Function"`).

Could you please test this for me?

For production use it's possibly better to use **1.4.2**-stable until the final 1.5.1-stable gets released.

Regards,
Stefan

[streamsupport-1.5.1-SNAPSHOT.zip](https://github.com/streamsupport/streamsupport/files/344593/streamsupport-1.5.1-SNAPSHOT.zip)

**Comment by stefan-zobel** [comment]
I've settled on `"android.opengl.GLES32$DebugProc"` rather than `"java.util.stream.BaseStream" - that's more future-proof. See the attached preview of 1.5.1

All tests in the streamsupport test suite pass on both Apache Harmony based Android and OpendJDK based Android (7.0, Nougat).

I consider this fixed now.

[streamsupport-1.5.1-SNAPSHOT.zip](https://github.com/streamsupport/streamsupport/files/348498/streamsupport-1.5.1-SNAPSHOT.zip)

**Comment by m3n4c3** [comment]
It's not fixed yet...

I tested it with the 1.5.1
I also tested for these classes:

exists ture/false:
true: android.util.DisplayMetrics
true: java.util.function.Function
false: android.opengl.GLES32$DebugProc
false: java.util.stream.BaseStream

AFAIK that is the desired output however it does not work yet...

Here is the Logcat Dump: (**this time on a google pixel with android 6**)

```
01-01 03:24:55.821: E/AndroidRuntime(3446): FATAL EXCEPTION: JavaFX Application Thread
01-01 03:24:55.821: E/AndroidRuntime(3446): Process: com.zeiss.forum.viewer.mobile.solln, PID: 3446
01-01 03:24:55.821: E/AndroidRuntime(3446): java.lang.Error: java.lang.NoSuchFieldException: No field elementData in class Ljava/util/ArrayList; (declaration of 'java.util.ArrayList' appears in /system/framework/core-libart.jar)
01-01 03:24:55.821: E/AndroidRuntime(3446): 	at java8.util.ArrayListSpliterator.<clinit>(ArrayListSpliterator.java:211)
01-01 03:24:55.821: E/AndroidRuntime(3446): 	at java8.util.Spliterators.listSpliterator(Spliterators.java:918)
01-01 03:24:55.821: E/AndroidRuntime(3446): 	at java8.util.Spliterators.spliterator(Spliterators.java:898)
01-01 03:24:55.821: E/AndroidRuntime(3446): 	at java8.util.stream.StreamSupport.stream(StreamSupport.java:99)

```

**Comment by stefan-zobel** [comment]
Hi. Thanks for testing. I'm baffled by your result.

Yes, "android.util.DisplayMetrics" => `true`, "android.opengl.GLES32$DebugProc" => `false` is the expected result on Android 6 and below.

To further track this down I need an absolutely minimal test case (Android Studio Project) that can reproduce this behavior.

**Comment by m3n4c3** [comment]
I can't supply you aith an Android Studio Project, since the sourcecode is Javafx not Android.
But I can give you an IntelliJ Idea Project (with gradle).

Javafxports compiles the javafx sourcecode and uses android to create an app.

I'm going to create it as soon as possible (hopefully i get it next week)

And you deserve a huge THANK YOU for answering so soon and trying to fix this :+1: .

**Comment by stefan-zobel** [comment]
Ok, I'll try with IntelliJ then (do you use the Gluon Mobile plugin?)

Another question: how do you run the `isClassPresent()` test? Is it called from a JavaFX application class? Immediately before you attempt

`StreamSupport.stream(someArrayList).forEach(someLamda)` ?

If not, could you try that please and tell me the result?

**Comment by m3n4c3** [comment]
Yes I use the gluon mobile plugin :)

And yes I do the tests immediately before calling the stream.

Another thing that might be useful:
In the main application I dont use streamsupport.
I use it in a library. I dont know if android handles libraries different than the main application...

Thank you :)

On July 8, 2016 1:01:38 PM GMT+02:00, stefan-zobel <notifications@github.com> wrote:
>Ok, I'll try with IntelliJ then (do you use the Gluon Mobile plugin?)
>
>Another question: how do you run the `isClassPresent()` test? Is it
>called from a JavaFX application class? Immediately before you attempt
>
>`StreamSupport.stream(someArrayList).forEach(someLamda)` ?
>
>If not, could you try that please and tell me the result?
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streamsupport/streamsupport/issues/4#issuecomment-231333246

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefan-zobel** [comment]
Thanks for your reply.

The only way I could imagine for such weird behavior to occur, is that the classloader that loads the streamsupport classes can't find `"android.util.DisplayMetrics"`. So streamsupport would think it is running on an ordinary JRE.

On Android, all "android." packages are in the bootclasspath. The normal app classloader will delegate to the built-in boot classloader to look them up.

If a "strange" classloader that decides to reject base Android classes is used to load the streamsupport classes, then that would explain the observed behavior. In that case we might be doomed ...

**Comment by m3n4c3** [comment]
Okay i'll have a closer look in the library and which classloader it uses.

Another idea I had.
If somebody uses your library he probably knows for which device/version/android etc he uses it.
What do you think about giving the user the option to set this value manually (and if he doesn't it will detect it like it is right now)?


On July 8, 2016 3:01:53 PM GMT+02:00, stefan-zobel <notifications@github.com> wrote:
>Thanks for your reply.
>
>The only way I could imagine for such weird behavior to occur, is that
>the classloader that loads the streamsupport classes can't find
>`"android.util.DisplayMetrics"`. So streamsupport would think it is
>running on an ordinary JRE.
>
>On Android, all "android." packages are in the bootclasspath. The
>normal app classloader will delegate to the built-in boot classloader
>to look them up.
>
>If a "strange" classloader that decides to reject base Android classes
>is used to load the streamsupport classes, then that would explain the
>observed behavior. In that case we might be doomed ...
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/streamsupport/streamsupport/issues/4#issuecomment-231353394

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefan-zobel** [comment]
Sure, an optional property would be a possibility.

There once was a (mandatory) property that had to be set on Android. Users complained about that, so I removed it and automated the detection process.

I've just read a little about using **_platform-specific_** code in JavaFXPorts. You realize, that using streamsupport on Android is in some sense platform-specific? Even though I don't use any Android APIs I must be able to **see** them (that is, DisplayMetrics and GLES32$DebugProc).

If it doesn't see them, it will assume the environment to be an OpenJDK-compatible JRE.

**Comment by stefan-zobel** [comment]
Assuming for a moment that my guess about the classloader is correct. The first thing we could do is querying

`System.getProperty("javafx.platform")`

That should return `"android"` if I understood that correctly (could you check this for me?).

That would solve the first problem: detecting whether we are on Android at all.

At this stage, streamsupport would assume an Apache Harmony based Android and this would be correct in your case.


The second problem is detecting whether our Android is actually Android 7 or above. I have no idea for this case yet. Maybe there is specific system property that can be used to figure this out.

Do you see the system properties from Android?

For example, what results (if any) do you get for the following properties:

`"android.icu.library.version"`
`"android.icu.unicode.version"`
`"android.icu.cldr.version"`


Thanks,
Stefan

**Comment by stefan-zobel** [comment]
Hi! I've done a test on JavaFXPorts myself now.

The test was run on a Pixel C running Android 6.0.1 (build MXC89H) following the steps in https://www.youtube.com/watch?v=cFZrXKFyGu8

That is, I've created the default "Gluon Mobile - Single View Project", added a plain-old Jar file "streamlib.jar" as my "library" and, of course, streamsupport itself.

"streamlib.jar" uses streamsupport internally and was compiled under Java 6. The "BasicView" JavaFX class in the sample project calls into the "streamlib" library and sets the Button label according to the result that gets returned from my method(s) in the "streamlib" library.

I can confirm that **_1.4.3 and 1.5 don't work_**.

However, **_1.4.2 and the current 1.5.1-SNAPSHOT work flawlessly_** in this test.

There is neither a classloader problem in that all interesting classes / interfaces are visible from within the "streamlib" library, nor is there any problem with streamsupport usage or its correct initialization.


So, I assume your "library" is either

**_a)_** something that is completely different from a "plain-old Jar", or

**_b)_** it uses a weird classloader that makes the "android." packages invisible, or

**_c)_** your latest test didn't actually install the 1.5.1-SNAPSHOT, but used the dysfunctional 1.4.3 again


I'm again inclined to believe that this problem has already been fixed ...

**Comment by m3n4c3** [comment]
Thank you for testing it yourself.

I believe for standard javafxports it is fixed.

However my Library still refuses to work.

It is very possible the library uses its own classloader.
Since I don't know much about Android Classloading itsself, have you any idea how I can test if everything is "normal"? Classloader - Classes loaded - etc?

Is there any workaround for trying to find out the platform its running on? - Maybe try to get access to fields and if it fails with an exception, try another one?

**Comment by stefan-zobel** [comment]
Just do the same thing I did as a first step: put the

`public boolean isClassPresent(String name)` method into your library

and call it with the "android.util.DisplayMetrics" and "android.opengl.GLES32$DebugProc" arguments from your JavaFX app. That should show you if there is a visibility problem from within your library.

Anyways, you should have the source of your app and your library - why not dig into it and see how it works?

**Comment by stefan-zobel** [comment]
Re: `"streamsupport version"` - there is no API to query the version at runtime. There are slight API differences between 1.4.2 and 1.4.3 (`j8.u.Maps`) and between 1.4.3 and 1.5/1.5.1 (`j8.u.Objects`) - but these are compile-time things.

Re: `"workarounds"` - currently not, and I'd refrain to do such a thing. I've already discussed this approach with Google engineers and we decided against it.

Another suggestion: why don't you simply change the streamsupport version in your grade config from 1.4.3 to 1.4.2 and see what happens?

**Comment by m3n4c3** [comment]
I tried that (version 1.4.2) and it didn't help either...

The Library is very, very, .... very big :) so I'd waste a whole lot of time searching through it.

However I can edit the source and check all the classes, I'll do that.

Thanks for your help

**Comment by stefan-zobel** [comment]
OK. You have to identify the _**root cause**_ of your issue before we can enter a discussion about potential workarounds.

On the face of it, only _**you**_ can do this - or provide a minimal "stripped to the bones" reproducer.

To me, it appears quite likely that streamsupport itself isn't responsible for your issue.

Question: on which platform has your "library" been used / tested before? Obviously it hasn't been Android.

**Comment by stefan-zobel** [comment]
There is another possible test you could do.

Instead of using a j.u.ArrayList, try with a `j.u.LinkedList` and show me the error you get.

It might be possible to infer something about the environment streamsupport believes to live in from this error.

**Comment by m3n4c3** [comment]
It's a library meant for desktop that i backported with your library
On Desktop it still works.

I'll edit the library to insert all these but it may take a little

Thank you, I'll be back when I have some results

**Comment by stefan-zobel** [comment]
More things to try (from your library): What does 

`isClassPresent("javafxports.android.DalvikLauncher")` return?

What is returned by

`Thread.currentThread().getContextClassLoader().getClass().getName()` and

`this.getClass().getClassLoader().getClass().getName()`

in your library immediately before the first call to streamsupport?

**Comment by stefan-zobel** [comment]
Any progress? I'd like to close this matter as soon as possible.

**Comment by m3n4c3** [comment]
```
01-08 01:56:02.274: W/System.err(9219): ### Class Present intern ###
01-08 01:56:02.275: W/System.err(9219): a) DisplayMetrics: true
01-08 01:56:02.275: W/System.err(9219): b) Function: true
01-08 01:56:02.277: W/System.err(9219): c) GLES32: false
01-08 01:56:02.278: W/System.err(9219): d) BaseStream: false
01-08 01:56:02.278: W/System.err(9219): e) DalvikLauncher: true
01-08 01:56:02.278: W/System.err(9219): f) ClassLoader Thread: dalvik.system.PathClassLoader
01-08 01:56:02.278: W/System.err(9219): f) ClassLoader this: dalvik.system.PathClassLoader
01-08 01:56:02.292: W/System.err(9219): ### Class Present library###
01-08 01:56:02.292: W/System.err(9219): a) DisplayMetrics: true
01-08 01:56:02.292: W/System.err(9219): b) Function: true
01-08 01:56:02.293: W/System.err(9219): c) GLES32: false
01-08 01:56:02.293: W/System.err(9219): d) BaseStream: false
01-08 01:56:02.293: W/System.err(9219): e) DalvikLauncher: true
01-08 01:56:02.293: W/System.err(9219): f) ClassLoader Thread: dalvik.system.PathClassLoader
01-08 01:56:02.293: W/System.err(9219): f) ClassLoader this: dalvik.system.PathClassLoader
```

Well... I did not expect that...
Again on Pixel C, with 1.5.1

**Comment by m3n4c3** [comment]
Ok nervermind I have found the Error:

Maven and Gradle pulled different Dependencies and overwrote each other - so even though the library used the newer version, the wrong library was used in the endapplication

Maven has problems building with 1.5.1 (probably because its a system path lib) but I used 1.4.2 and now it works.

Thank you for all your patience and help.
It is fixed :D

**Comment by stefan-zobel** [comment]
I almost expected something like that (and the stacktrace caused by a j.u.LinkedList would have proven it).

Closed this as "fixed".

**Comment by stefan-zobel** [comment]
Please note that 1.5.1-stable has been released just now. I'd recommend to upgrade to 1.5.1.
